#!/usr/bin/env python3

from text_to_sql_agent import create_text_to_sql_agent

def run_demo():
    """Demonstrate the text-to-SQL agent with various queries"""
    print("🎵 LangGraph Text-to-SQL Agent Demo")
    print("=" * 50)
    
    agent = create_text_to_sql_agent()
    
    demo_queries = [
        ("Valid business question", "What are the top 3 albums by sales revenue?"),
        ("Customer analysis", "Which countries have more than 3 customers?"),
        ("Music analysis", "What is the average track length in Rock genre?"),
        ("Employee query", "How many employees work as Sales Support Agent?"),
        ("Irrelevant question", "What is the weather like today?"),
        ("Complex aggregation", "What is the total revenue generated by each genre?")
    ]
    
    for category, query in demo_queries:
        print(f"\n📋 {category}")
        print(f"🤔 Question: {query}")
        print("-" * 40)
        
        try:
            result = agent.invoke({
                "user_query": query,
                "sql_query": "",
                "sql_result": "",
                "natural_language_response": "",
                "error": ""
            })
            
            print(f"💬 Answer: {result['natural_language_response']}")
            
            if result.get("sql_query"):
                print(f"🔍 SQL: {result['sql_query']}")
            
            if result.get("error"):
                print(f"⚠️  Error: {result['error']}")
                
        except Exception as e:
            print(f"❌ Exception: {e}")
        
        print("=" * 50)

if __name__ == "__main__":
    run_demo()